{"name": "test_login_wrong_pws_manytime", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in module-scoped context", "trace": "request = <SubRequest 'setup_and_teardown' for <Function test_login_valid_user>>\n\n    @pytest.fixture(scope=\"module\")\n    def setup_and_teardown(request):\n        wdf = WebDriverFactory()\n        browser = get_browser(request)\n        target = get_target(request)\n        driver = wdf.get_driver(browser, target)\n    \n>       if request.cls is not None:\nE       AttributeError: cls not available in module-scoped context\n\ntests\\conftest.py:20: AttributeError"}, "description": "\n        System shows message when user enters wrong password many times.\n        :return:\n        ", "start": 1721027609817, "stop": 1721027609817, "uuid": "77691065-7700-4732-b4a8-f5299059a332", "historyId": "4e96d6e7442c6f05e9317ee924afd076", "testCaseId": "4e96d6e7442c6f05e9317ee924afd076", "fullName": "tests.test_login.TestLogin#test_login_wrong_pws_manytime", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DUYEN"}, {"name": "thread", "value": "25976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}